In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [78]:
df = pd.read_csv("../data/pet.csv", encoding="utf-8", index_col=0)
df

     자치구      계    내장형    외장형   인식표
연번
1    종로구  10821   4892   4575  1354
2     중구   8985   4663   3846   476
3    용산구  19518  10920   7061  1537
4    성동구  18904   9560   7019  2325
5    광진구  22894  11556  10064  1274
6   동대문구  21497  10052  10339  1106
7    중랑구  26631  12605  10997  3029
8    성북구  27512  12756  12640  2116
9    강북구  21414  10432   7892  3090
10   도봉구  22760   9167  11780  1813
11   노원구  30989  13165  15679  2145
12   은평구  32261  15630  13290  3341
13  서대문구  20292  10069   8813  1410
14   마포구  25976  14198  10058  1720
15   양천구  27287  14127  11361  1799
16   강서구  38447  16757  18094  3596
17   구로구  22284  11193   9298  1793
18   금천구  14968   6649   7322   997
19  영등포구  21832   9593   9988  2251
20   동작구  20758   9411   9492  1855
21   관악구  30158  13661  11923  4574
22   서초구  27160  13817  11189  2154
23   강남구  40936  19369  17963  3604
24   송파구  38740  18693  16899  3148
25   강동구  29113  13967  13790  1356

In [82]:
df["계"].sum()

np.int64(622137)